spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      bootstrap-servers: kafka:9092
      group-id: notification-group

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.orderplatform.notification_service.event.OrderCreatedEvent

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8082