services:

  postgres:
    image: postgres:16
    container_name: order-platform-postgres
    environment:
      POSTGRES_DB: order_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7
    container_name: order-platform-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

  app:
    build:
      context: ./order-service

    container_name: order-platform-app

    depends_on:
      - postgres
      - redis
      - kafka

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_platform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      JWT_SECRET: mySuperSecretKeyMySuperSecretKey123

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  kafka:
    image: confluentinc/cp-kafka:7.6.1

    container_name: order-platform-kafka

    ports:
      - "9092:9092"

    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qg

      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data

    restart: unless-stopped

  prometheus:
    image: prom/prometheus

    container_name: order-platform-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    restart: unless-stopped

  grafana:
    image: grafana/grafana

    container_name: order-platform-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service

    container_name: notification-service

    depends_on:
      - kafka

    ports:
      - "8082:8082"

    restart: unless-stopped

  gateway-service:
    build:
      context: ./gateway-service

    container_name: gateway-service

    ports:
      - "8080:8080"

    depends_on:
      - app

volumes:
  postgres_data:
  kafka_data: