services:

  postgres:
    image: postgres:16
    container_name: order-platform-postgres
    environment:
      POSTGRES_DB: order_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7
    container_name: order-platform-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

  app:
    build: .

    container_name: order-platform-app

    depends_on:
      - postgres
      - redis

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_platform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_SECRET: mySuperSecretKeyMySuperSecretKey123

volumes:
  postgres_data: