server:
  port: 8085

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: payment-result-group-v2
      auto-offset-reset: latest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "com.orderplatform.*"
        spring.json.value.default.type: com.orderplatform.payment_service.event.PaymentRequestedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false