spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/order_platform?options=-c%20TimeZone=Europe/Kyiv
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true

  jackson:
    time-zone: Europe/Kyiv

  kafka:
    bootstrap-servers: kafka:9092

    listener:
      missing-topics-fatal: false

    admin:
      auto-create: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: order-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

jwt:
  secret: mySuperSecretKeyMySuperSecretKey123

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"

server:
  port: 8081

cache:
  ttl-minutes: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true