spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/order_platform?options=-c%20TimeZone=Europe/Kyiv
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8081