server:
  port: 8084

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://postgres:5432/order_platform
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: inventory

    show-sql: false

  flyway:
    enabled: true
    schemas: inventory
    default-schema: inventory
    table: inventory_flyway_schema_history

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false
        interceptor.classes: com.orderplatform.inventory_service.tracing.KafkaTraceProducerInterceptor


    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >-
          inventoryReserveRequest:com.orderplatform.inventory_service.event.InventoryReserveRequestEvent,
          inventoryReleaseRequested:com.orderplatform.inventory_service.event.InventoryReleaseRequestedEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"